# Generated by Django 5.0 on 2024-01-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_profession_alter_profile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
