# Generated by Django 5.0 on 2024-01-03 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
