# Generated by Django 5.0 on 2023-12-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_blogpost_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user',
            new_name='author',
        ),
    ]
