# Generated by Django 5.0 on 2023-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_after_me',
            field=models.BooleanField(default=False),
        ),
    ]
