# Generated by Django 5.0 on 2024-01-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_blogpost_banner_after_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
    ]
