# Generated by Django 5.0 on 2024-01-04 19:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2024, 1, 4))),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.blogpost')),
            ],
            options={
                'unique_together': {('blog_post', 'date')},
            },
        ),
    ]
