# Generated by Django 5.0 on 2024-01-05 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_delete_dailyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_image', models.ImageField(blank=True, default='insta_images/default_insta_image.png', null=True, upload_to='insta_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])])),
                ('insta_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
