# Generated by Django 5.0 on 2024-01-24 12:41

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
