# Generated by Django 5.0 on 2024-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_blogpost_content_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
