# Generated by Django 5.0 on 2024-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(to='post.blogpost'),
        ),
    ]
