# Generated by Django 5.0 on 2024-01-01 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=300)),
                ('ad_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
